version: '3'
services:
  app:
    build:
      context: ./
    tty: true
    working_dir: /opt/server
    volumes:
      - ./app:/opt/server
      - ./dist:/opt/static
    env_file:
      - .env
    ports:
      - '80:8080'
    depends_on:
      - db

  db:
    image: postgres:12-alpine
    env_file:
      - .env
    volumes:
      - ./compose/data/dump/:/docker-entrypoint-initdb.d
    ports:
      - '5432:5432'
    restart: always

  pgadmin:
    container_name: pgadmin
    depends_on:
      - db
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: chupurnov@gmail.com
      PGADMIN_DEFAULT_PASSWORD: qwertyuiop
    ports:
      - '8999:80'
    restart: always
