openapi: '3.0.1'
info:
    version: v1
    title: Mappable test server
    license:
        name: 'Apache-2'
paths:
    /version:
        get:
            description: Application Version
            responses:
                200:
                    description: Version
                    content:
                        application/json:
                            example: {'version': '1.0.0'}
                            schema:
                                type: object
                                properties:
                                    version:
                                        type: string

    /ping:
        get:
            description: |
                Handle for checking the readiness of the server to work
            responses:
                200:
                    description: Server is ready.
                    content:
                        application/json:
                            example: {'ok': true}
                            schema:
                                type: object
                                properties:
                                    ok:
                                        type: boolean
                400:
                    description: Server is not ready.
                    content:
                        application/json:
                            example: {'ok': false}
                            schema:
                                type: object
                                properties:
                                    ok:
                                        type: boolean

    /v1/bbox:
        post:
            description: |
                Returns geo features whose coordinates are within the given rectangle bbox

            requestBody:
                description:
                    JSON object
                required: true
                content:
                    application/json:
                        schema:
                            allOf:
                                - $ref: '#/components/schemas/PageRequest'
                                - type: object
                                  required: ['leftBottom', 'rightTop']
                                  example: {
                                      limit: 1000,
                                      page: 1,
                                      leftBottom: [-100, 100],
                                      rightTop: [100, -100]
                                  }
                                  properties:
                                      limit:
                                          type: integer
                                      page:
                                          type: integer
                                      leftBottom:
                                          $ref: '#/components/schemas/LngLat'
                                      rightTop:
                                          $ref: '#/components/schemas/LngLat'

            responses:
                200:
                    description: Features list.
                    content:
                        application/json:
                            schema:
                                $ref: '#/components/schemas/Features'

                400:
                    $ref: '#/components/responses/InvalidParameters'

    /v1/tile:
        post:
            description: |
                Returns geo features whose coordinates are within a rectangle that is uniquely defined by its x,y and z tile coordinates

            requestBody:
                content:
                    application/json:
                        schema:
                            allOf:
                                - $ref: '#/components/schemas/PageRequest'
                                - type: object
                                  properties:
                                      x:
                                          type: integer
                                          required: true
                                      y:
                                          type: integer
                                          required: true
                                      z:
                                          type: integer
                                          required: true

                description: JSON object

            responses:
                200:
                    description: Features list.
                    content:
                        application/json:
                            schema:
                                $ref: '#/components/schemas/FeaturesWithBounds'

                400:
                    $ref: '#/components/responses/InvalidParameters'

components:
    responses:
        InvalidParameters:
            description: Invalid parameters.
            content:
                application/json:
                    schema:
                        $ref: '#/components/schemas/Error'

    schemas:
        LngLat:
            description: 'Array of coordinates [Longitude, Latitude].'
            example: [24, 54]
            type: array
            items:
                type: number
            minItems: 2
            maxItems: 2

        PageRequest:
            description: 'Page and limits'
            type: object
            properties:
                limit:
                    type: integer
                    minimum: 100
                    maximum: 10000
                page:
                    type: integer
                    minimum: 1

        Feature:
            description: 'GeoJSON Feature'
            type: object
            example:
                {
                    type: 'Feature',
                    properties: {name: 'Abu Dhabi'},
                    geometry: {'type': 'Point', 'coordinates': [24.189215755000077, 53.796540969000034]}
                }
            properties:
                type:
                    type: string
                properties:
                    type: object
                    properties:
                        name:
                            type: string
                geometry:
                    type: object
                    properties:
                        type:
                            type: string
                        coordinates:
                            $ref: '#/components/schemas/LngLat'

        Features:
            type: object
            properties:
                total:
                    type: integer
                features:
                    type: array
                    items:
                        $ref: '#/components/schemas/Feature'

        FeaturesWithBounds:
            allOf:
                - $ref: '#/components/schemas/Features'
                - type: object
                  properties:
                      bounds:
                          description: Computed rectangle of coordinates lower left and upper right corner for a given tile
                          type: array
                          minLength: 2
                          maxLength: 2
                          items:
                              $ref: '#/components/schemas/LngLat'

        Error:
            type: object
            properties:
                statusCode:
                    type: integer
                error:
                    type: string
                message:
                    type: string
            required:
                - statusCode
                - error
                - message
            additionalProperties: false
