openapi: '3.0.1'
info:
    version: v1
    title: Mappable test server
    license:
        name: 'Apache-2'

paths:
    /v1/bbox:
        get:
            summary: |
                Returns geo features whose coordinates are within the given rectangle bbox

            parameters:
                - in: query
                  name: lng1
                  schema:
                      type: number
                  required: true
                  example: 23.5
                  description: Longitude of the lower left corner of the rectangle

                - in: query
                  name: lat1
                  schema:
                      type: number
                  required: true
                  example: 53.5
                  description: Latitude of the lower left corner of the rectangle

                - in: query
                  name: lng2
                  schema:
                      type: number
                  required: true
                  example: 24.5
                  description: Longitude of the upper right corner of the rectangle

                - in: query
                  name: lat2
                  schema:
                      type: number
                  required: true
                  example: 54.5
                  description: Latitude of the upper right corner of the rectangle

                - in: query
                  name: limit
                  schema:
                      type: number
                  required: false
                  example: 100
                  description: Limit of features to return

                - in: query
                  name: page
                  schema:
                      type: number
                      minimum: 1
                  required: false
                  example: 1
                  description: Page number

            responses:
                200:
                    description: Features list.
                    content:
                        application/json:
                            schema:
                                $ref: '#/components/schemas/Features'

                400:
                    $ref: '#/components/responses/InvalidParameters'

    /v1/tile:
        get:
            summary: |
                Returns geo features whose coordinates are within a rectangle that is uniquely defined by its x,y and z tile coordinates

            parameters:
                - in: query
                  name: x
                  schema:
                      type: integer
                  required: true
                  example: 10

                - in: query
                  name: y
                  schema:
                      type: integer
                  required: true
                  example: 20

                - in: query
                  name: z
                  schema:
                      type: integer
                  required: true
                  example: 5

            responses:
                200:
                    description: Features list.
                    content:
                        application/json:
                            schema:
                                $ref: '#/components/schemas/FeaturesWithBounds'

                400:
                    $ref: '#/components/responses/InvalidParameters'

    /version:
        get:
            description: Application Version
            responses:
                200:
                    description: Version
                    content:
                        application/json:
                            example: {'version': '1.0.0'}
                            schema:
                                type: object
                                properties:
                                    version:
                                        type: string

    /ping:
        get:
            description: |
                Handle for checking the readiness of the server to work
            responses:
                200:
                    description: Server is ready.
                    content:
                        application/json:
                            example: {'ok': true}
                            schema:
                                type: object
                                properties:
                                    ok:
                                        type: boolean
                400:
                    description: Server is not ready.
                    content:
                        application/json:
                            example: {'ok': false}
                            schema:
                                type: object
                                properties:
                                    ok:
                                        type: boolean

components:
    responses:
        InvalidParameters:
            description: Invalid parameters.
            content:
                application/json:
                    schema:
                        $ref: '#/components/schemas/Error'

    schemas:
        LngLat:
            description: 'Array of coordinates [Longitude, Latitude].'
            example: [24, 54]
            type: array
            items:
                type: number
            minItems: 2
            maxItems: 2

        Feature:
            description: 'GeoJSON Feature'
            type: object
            example:
                {
                    type: 'Feature',
                    properties: {name: 'Abu Dhabi'},
                    geometry: {'type': 'Point', 'coordinates': [24.189215755000077, 53.796540969000034]}
                }
            properties:
                type:
                    type: string
                properties:
                    type: object
                    properties:
                        name:
                            type: string
                geometry:
                    type: object
                    properties:
                        type:
                            type: string
                        coordinates:
                            $ref: '#/components/schemas/LngLat'

        Features:
            type: object
            properties:
                total:
                    type: integer
                features:
                    type: array
                    items:
                        $ref: '#/components/schemas/Feature'

        FeaturesWithBounds:
            allOf:
                - $ref: '#/components/schemas/Features'
                - type: object
                  properties:
                      bounds:
                          description: Computed rectangle of coordinates lower left and upper right corner for a given tile
                          type: array
                          minLength: 2
                          maxLength: 2
                          items:
                              $ref: '#/components/schemas/LngLat'

        Error:
            type: object
            properties:
                statusCode:
                    type: integer
                error:
                    type: string
                message:
                    type: string
            required:
                - statusCode
                - error
                - message
            additionalProperties: false
